USE leveluplearning_db;

insert into subjects (name) values('10th Grade');
insert into subjects (name) values('10th Grade Math');
insert into subjects (name) values('10th Grade Reading');
insert into subjects (name) values('10th Grade Writing');
insert into subjects (name) values('11th Grade');
insert into subjects (name) values('11th Grade Math');
insert into subjects (name) values('11th Grade Reading');
insert into subjects (name) values('11th Grade Writing');
insert into subjects (name) values('12th Grade');
insert into subjects (name) values('12th Grade Math');
insert into subjects (name) values('12th Grade Reading');
insert into subjects (name) values('12th Grade Writing');
insert into subjects (name) values('1st Grade');
insert into subjects (name) values('1st Grade Math');
insert into subjects (name) values('1st Grade Reading');
insert into subjects (name) values('1st Grade Writing');
insert into subjects (name) values('2nd Grade');
insert into subjects (name) values('2nd Grade Math');
insert into subjects (name) values('2nd Grade Reading');
insert into subjects (name) values('2nd Grade Writing');
insert into subjects (name) values('3rd Grade');
insert into subjects (name) values('3rd Grade Math');
insert into subjects (name) values('3rd Grade Reading');
insert into subjects (name) values('3rd Grade Science');
insert into subjects (name) values('3rd Grade Writing');
insert into subjects (name) values('4th Grade');
insert into subjects (name) values('4th Grade Math');
insert into subjects (name) values('4th Grade Reading');
insert into subjects (name) values('4th Grade Science');
insert into subjects (name) values('4th Grade Writing');
insert into subjects (name) values('5th Grade');
insert into subjects (name) values('5th Grade Math');
insert into subjects (name) values('5th Grade Reading');
insert into subjects (name) values('5th Grade Science');
insert into subjects (name) values('5th Grade Writing');
insert into subjects (name) values('6th Grade');
insert into subjects (name) values('6th Grade Math');
insert into subjects (name) values('6th Grade Reading');
insert into subjects (name) values('6th Grade Science');
insert into subjects (name) values('6th Grade Writing');
insert into subjects (name) values('7th Grade');
insert into subjects (name) values('7th Grade Math');
insert into subjects (name) values('7th Grade Reading');
insert into subjects (name) values('7th Grade Science');
insert into subjects (name) values('7th Grade Writing');
insert into subjects (name) values('8th Grade');
insert into subjects (name) values('8th Grade Math');
insert into subjects (name) values('8th Grade Reading');
insert into subjects (name) values('8th Grade Science');
insert into subjects (name) values('8th Grade Writing');
insert into subjects (name) values('9th Grade');
insert into subjects (name) values('9th Grade Math');
insert into subjects (name) values('9th Grade Reading');
insert into subjects (name) values('9th Grade Writing');
insert into subjects (name) values('Accounting');
insert into subjects (name) values('ACCUPLACER Arithmetic');
insert into subjects (name) values('ACCUPLACER College-Level Math');
insert into subjects (name) values('ACCUPLACER Elementary Algebra');
insert into subjects (name) values('ACCUPLACER ESL');
insert into subjects (name) values('ACCUPLACER Reading Comprehension');
insert into subjects (name) values('ACCUPLACER Sentence Skills');
insert into subjects (name) values('ACCUPLACER WritePlacer');
insert into subjects (name) values('ACT');
insert into subjects (name) values('ADD');
insert into subjects (name) values('ADHD');
insert into subjects (name) values('Advanced Placement');
insert into subjects (name) values('African History');
insert into subjects (name) values('African-American History');
insert into subjects (name) values('Agricultural Science');
insert into subjects (name) values('Algebra 1');
insert into subjects (name) values('Algebra 2');
insert into subjects (name) values('Algorithms');
insert into subjects (name) values('American History');
insert into subjects (name) values('American Literature');
insert into subjects (name) values('American Sign Language');
insert into subjects (name) values('Analytical Chemistry');
insert into subjects (name) values('Anatomy');
insert into subjects (name) values('Anthropology');
insert into subjects (name) values('AP Art History');
insert into subjects (name) values('AP Biology');
insert into subjects (name) values('AP Calculus AB');
insert into subjects (name) values('AP Calculus BC');
insert into subjects (name) values('AP Chemistry');
insert into subjects (name) values('AP Chinese');
insert into subjects (name) values('AP Chinese Language and Culture');
insert into subjects (name) values('AP Comparative Government and Politics');
insert into subjects (name) values('AP Computer Science');
insert into subjects (name) values('AP English Language and Composition');
insert into subjects (name) values('AP English Literature and Composition');
insert into subjects (name) values('AP Environmental Science');
insert into subjects (name) values('AP European History');
insert into subjects (name) values('AP French');
insert into subjects (name) values('AP French Language and Culture');
insert into subjects (name) values('AP German Language and Culture');
insert into subjects (name) values('AP Human Geography');
insert into subjects (name) values('AP Italian Language and Culture');
insert into subjects (name) values('AP Japanese Language and Culture');
insert into subjects (name) values('AP Latin');
insert into subjects (name) values('AP Macroeconomics');
insert into subjects (name) values('AP Microeconomics');
insert into subjects (name) values('AP Music Theory');
insert into subjects (name) values('AP Physics');
insert into subjects (name) values('AP Psychology');
insert into subjects (name) values('AP Statistics');
insert into subjects (name) values('AP Studio Art');
insert into subjects (name) values('AP U.S. Government &amp; Politics');
insert into subjects (name) values('AP United States History');
insert into subjects (name) values('AP US Government');
insert into subjects (name) values('AP US History');
insert into subjects (name) values('AP World History');
insert into subjects (name) values('Applied Mathematics');
insert into subjects (name) values('Arabic');
insert into subjects (name) values('Architectural Design');
insert into subjects (name) values('Architecture');
insert into subjects (name) values('Arithmetic');
insert into subjects (name) values('Art');
insert into subjects (name) values('ASVAB');
insert into subjects (name) values('Autism');
insert into subjects (name) values('Bass Guitar');
insert into subjects (name) values('Biochemistry');
insert into subjects (name) values('Biology');
insert into subjects (name) values('Biomechanics');
insert into subjects (name) values('Biomedical Engineering');
insert into subjects (name) values('Biostatistics');
insert into subjects (name) values('Biotechnology');
insert into subjects (name) values('British Literature');
insert into subjects (name) values('Business');
insert into subjects (name) values('Business Enterprise');
insert into subjects (name) values('Business Statistics');
insert into subjects (name) values('C++');
insert into subjects (name) values('Calculus');
insert into subjects (name) values('Cantonese');
insert into subjects (name) values('CSS-Cascading Style Sheets');
insert into subjects (name) values('Cell Biology');
insert into subjects (name) values('Cello');
insert into subjects (name) values('Ceramics');
insert into subjects (name) values('Chemical Engineering');
insert into subjects (name) values('Chemistry');
insert into subjects (name) values('Chinese');
insert into subjects (name) values('Civics');
insert into subjects (name) values('Civil and Environmental Engineering');
insert into subjects (name) values('Civil Engineering');
insert into subjects (name) values('Clarinet');
insert into subjects (name) values('College Algebra');
insert into subjects (name) values('College Essays');
insert into subjects (name) values('COMPASS Mathematics');
insert into subjects (name) values('COMPASS Reading');
insert into subjects (name) values('COMPASS Writing Skills');
insert into subjects (name) values('Computer Animation');
insert into subjects (name) values('Computer Game Design');
insert into subjects (name) values('Computer Programming');
insert into subjects (name) values('Computer Science');
insert into subjects (name) values('Computer Skills');
insert into subjects (name) values('Creative Writing');
insert into subjects (name) values('Czech');
insert into subjects (name) values('Differential Equations');
insert into subjects (name) values('Digital Media');
insert into subjects (name) values('Drawing');
insert into subjects (name) values('Drum and Percussion');
insert into subjects (name) values('Dutch');
insert into subjects (name) values('Dyslexia');
insert into subjects (name) values('Economics');
insert into subjects (name) values('Electrical and Computer Engineering');
insert into subjects (name) values('Electrical Engineering');
insert into subjects (name) values('Elementary Algebra');
insert into subjects (name) values('Elementary Math');
insert into subjects (name) values('Engineering');
insert into subjects (name) values('English');
insert into subjects (name) values('ESL/ELL');
insert into subjects (name) values('Essay Editing');
insert into subjects (name) values('Fiction Writing');
insert into subjects (name) values('Film');
insert into subjects (name) values('Finance');
insert into subjects (name) values('Finite Mathematics');
insert into subjects (name) values('Finnish');
insert into subjects (name) values('Flute');
insert into subjects (name) values('Foreign Language');
insert into subjects (name) values('French');
insert into subjects (name) values('Gastroenterology');
insert into subjects (name) values('GED');
insert into subjects (name) values('Geography');
insert into subjects (name) values('Geology');
insert into subjects (name) values('Geometry');
insert into subjects (name) values('German');
insert into subjects (name) values('Gifted');
insert into subjects (name) values('Government');
insert into subjects (name) values('Grammar and Mechanics');
insert into subjects (name) values('Graphic Design');
insert into subjects (name) values('Greek');
insert into subjects (name) values('Guitar');
insert into subjects (name) values('Handwriting');
insert into subjects (name) values('Health Care Policy');
insert into subjects (name) values('Hebrew');
insert into subjects (name) values('History');
insert into subjects (name) values('Homeschool');
insert into subjects (name) values('Honors');
insert into subjects (name) values('HTML');
insert into subjects (name) values('Hungarian');
insert into subjects (name) values('Industrial Engineering');
insert into subjects (name) values('Intermediate Accounting');
insert into subjects (name) values('Intermediate Algebra');
insert into subjects (name) values('Italian');
insert into subjects (name) values('Japanese');
insert into subjects (name) values('Java');
insert into subjects (name) values('JavaScript');
insert into subjects (name) values('JQuery');
insert into subjects (name) values('Kindergarten - 8th Grade');
insert into subjects (name) values('Korean');
insert into subjects (name) values('Laboratory');
insert into subjects (name) values('Languages');
insert into subjects (name) values('Latin');
insert into subjects (name) values('Latin America History');
insert into subjects (name) values('Law');
insert into subjects (name) values('Legal Research');
insert into subjects (name) values('Legal Writing');
insert into subjects (name) values('Life Sciences');
insert into subjects (name) values('Linear Algebra');
insert into subjects (name) values('Linguistics');
insert into subjects (name) values('Literature');
insert into subjects (name) values('LSAT');
insert into subjects (name) values('Macroeconomics');
insert into subjects (name) values('Management');
insert into subjects (name) values('Mandarin Chinese');
insert into subjects (name) values('Marketing');
insert into subjects (name) values('Math');
insert into subjects (name) values('Mathematical Foundations for Computer Science');
insert into subjects (name) values('Mechanical Engineering');
insert into subjects (name) values('Medical Terminology');
insert into subjects (name) values('Microbiology');
insert into subjects (name) values('Microeconomics');
insert into subjects (name) values('Middle School');
insert into subjects (name) values('Middle School Math');
insert into subjects (name) values('Music');
insert into subjects (name) values('Neuroscience');
insert into subjects (name) values('Newtonian Mechanics');
insert into subjects (name) values('Nutrition');
insert into subjects (name) values('Operating Systems');
insert into subjects (name) values('Organic Chemistry');
insert into subjects (name) values('Organization');
insert into subjects (name) values('Other');
insert into subjects (name) values('Painting');
insert into subjects (name) values('Persuasive Writing');
insert into subjects (name) values('Phonics');
insert into subjects (name) values('Photography');
insert into subjects (name) values('PHP');
insert into subjects (name) values('Physical Chemistry');
insert into subjects (name) values('Physical Science');
insert into subjects (name) values('Physics');
insert into subjects (name) values('Piano');
insert into subjects (name) values('Plant Biology');
insert into subjects (name) values('Poetry Writing');
insert into subjects (name) values('Polish');
insert into subjects (name) values('Political Science');
insert into subjects (name) values('Pre-Algebra');
insert into subjects (name) values('Pre-Calculus');
insert into subjects (name) values('Probability');
insert into subjects (name) values('Programming');
insert into subjects (name) values('Programming VB.NET');
insert into subjects (name) values('Public Speaking');
insert into subjects (name) values('Python');
insert into subjects (name) values('Quantitative Reasoning');
insert into subjects (name) values('Quantum Mechanics');
insert into subjects (name) values('Quantum Physics');
insert into subjects (name) values('Quantum Theory');
insert into subjects (name) values('Reading');
insert into subjects (name) values('Religious Studies');
insert into subjects (name) values('Romanian');
insert into subjects (name) values('Ruby');
insert into subjects (name) values('Russian');
insert into subjects (name) values('SAT');
insert into subjects (name) values('SAT Subject Tests');
insert into subjects (name) values('Saxophone');
insert into subjects (name) values('Science');
insert into subjects (name) values('Scientific Programming');
insert into subjects (name) values('Sculpture');
insert into subjects (name) values('Shakespeare');
insert into subjects (name) values('Short Novel');
insert into subjects (name) values('Singing');
insert into subjects (name) values('Social Studies');
insert into subjects (name) values('Sociology');
insert into subjects (name) values('Software');
insert into subjects (name) values('Software Engineering');
insert into subjects (name) values('Spanish');
insert into subjects (name) values('Special Education');
insert into subjects (name) values('SQL');
insert into subjects (name) values('SSAT- Elementary Level');
insert into subjects (name) values('SSAT- Middle Level');
insert into subjects (name) values('SSAT- Upper Level');
insert into subjects (name) values('STAAR');
insert into subjects (name) values('STAAR Grades 3-8');
insert into subjects (name) values('Statistics');
insert into subjects (name) values('Structural Engineering');
insert into subjects (name) values('Study Skills');
insert into subjects (name) values('Study Skills And Organization');
insert into subjects (name) values('Summer Tutoring');
insert into subjects (name) values('Technical Writing');
insert into subjects (name) values('Technology and Computer Science');
insert into subjects (name) values('Test Prep');
insert into subjects (name) values('Trigonometry');
insert into subjects (name) values('US Constitutional History');
insert into subjects (name) values('US History');
insert into subjects (name) values('Violin');
insert into subjects (name) values('Vocabulary');
insert into subjects (name) values('Voice');
insert into subjects (name) values('Web Design');
insert into subjects (name) values('Web Development');
insert into subjects (name) values('World Civilization');
insert into subjects (name) values('World History');
insert into subjects (name) values('Writing');